In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Load file
df = pd.read_csv('loan_data Python Data2.csv')

# 1. Calculate Monthly Income from the Log Annual Income
import numpy as np
df['Monthly Income'] = np.exp(df['Log Annual Income']) / 12

# 2. Monthly Debt-to-Income Payment Ratio
# How much of their monthly take-home pay goes JUST to this loan?
df['Installment_as_Pct_Income'] = df['Installments'] / df['Monthly Income']

df.head()

,Credit Policy,Interest Rate,Installments,Log Annual Income,Annual Income,Debt to Income Ratio,FICO Score,Days with Credit Line,Revolving Balance,Revolving Utilization,...,Public Records,Not Fully Paid,Purpose Credit Card,Purpose Debt Consolidation,Purpose Educational,Purpose Home Improvement,Purpose Major Purchase,Purpose Small Business,Monthly Income,Installment_as_Pct_Income
0,1,0.1189,829.10,11.350407,85000.00038,0.1948,737,5640,28854,0.521,...,0,0,0,1,0,0,0,0,7083.333365,0.117049
1,1,0.1071,228.22,11.082143,65000.00007,0.1429,707,2760,33623,0.767,...,0,0,1,0,0,0,0,0,5416.666673,0.042133
2,1,0.1357,366.86,10.373491,31999.99994,0.1163,682,4710,3511,0.256,...,0,0,0,1,0,0,0,0,2666.666662,0.137573
3,1,0.1008,162.34,11.350407,85000.00038,0.0810,712,2700,33667,0.732,...,0,0,0,1,0,0,0,0,7083.333365,0.022919
4,1,0.1426,102.92,11.299732,80799.99964,0.1497,667,4066,4740,0.395,...,0,0,1,0,0,0,0,0,6733.333303,0.015285

In [4]:
# 3. Move the desired column
# Remove the column from its original position
column_to_move = df.pop('Monthly Income')

# Insert the column at the desired index (e.g., index 0 for the start, index 2 for the third position)
desired_position_index = 5
df.insert(desired_position_index, column_to_move.name, column_to_move)

In [5]:
df.head()

,Credit Policy,Interest Rate,Installments,Log Annual Income,Annual Income,Monthly Income,Debt to Income Ratio,FICO Score,Days with Credit Line,Revolving Balance,...,Delinquencies 2 Years,Public Records,Not Fully Paid,Purpose Credit Card,Purpose Debt Consolidation,Purpose Educational,Purpose Home Improvement,Purpose Major Purchase,Purpose Small Business,Installment_as_Pct_Income
0,1,0.1189,829.10,11.350407,85000.00038,7083.333365,0.1948,737,5640,28854,...,0,0,0,0,1,0,0,0,0,0.117049
1,1,0.1071,228.22,11.082143,65000.00007,5416.666673,0.1429,707,2760,33623,...,0,0,0,1,0,0,0,0,0,0.042133
2,1,0.1357,366.86,10.373491,31999.99994,2666.666662,0.1163,682,4710,3511,...,0,0,0,0,1,0,0,0,0,0.137573
3,1,0.1008,162.34,11.350407,85000.00038,7083.333365,0.0810,712,2700,33667,...,0,0,0,0,1,0,0,0,0,0.022919
4,1,0.1426,102.92,11.299732,80799.99964,6733.333303,0.1497,667,4066,4740,...,1,0,0,1,0,0,0,0,0,0.015285

In [6]:
# 3. Move the desired column
# Remove the column from its original position
column_to_move = df.pop('Installment_as_Pct_Income')

# Insert the column at the desired index (e.g., index 0 for the start, index 2 for the third position)
desired_position_index = 3
df.insert(desired_position_index, column_to_move.name, column_to_move)
df.head()

,Credit Policy,Interest Rate,Installments,Installment_as_Pct_Income,Log Annual Income,Annual Income,Monthly Income,Debt to Income Ratio,FICO Score,Days with Credit Line,...,Inquiries Last 6 Months,Delinquencies 2 Years,Public Records,Not Fully Paid,Purpose Credit Card,Purpose Debt Consolidation,Purpose Educational,Purpose Home Improvement,Purpose Major Purchase,Purpose Small Business
0,1,0.1189,829.10,0.117049,11.350407,85000.00038,7083.333365,0.1948,737,5640,...,0,0,0,0,0,1,0,0,0,0
1,1,0.1071,228.22,0.042133,11.082143,65000.00007,5416.666673,0.1429,707,2760,...,0,0,0,0,1,0,0,0,0,0
2,1,0.1357,366.86,0.137573,10.373491,31999.99994,2666.666662,0.1163,682,4710,...,1,0,0,0,0,1,0,0,0,0
3,1,0.1008,162.34,0.022919,11.350407,85000.00038,7083.333365,0.0810,712,2700,...,1,0,0,0,0,1,0,0,0,0
4,1,0.1426,102.92,0.015285,11.299732,80799.99964,6733.333303,0.1497,667,4066,...,0,1,0,0,1,0,0,0,0,0

In [7]:
# 3. Save to a new CSV file
# 'index=False' prevents Pandas from adding a new column for row numbers
df.to_csv('loan_data Python Data3.csv', index=False)

In [11]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Load file
df = pd.read_csv('loan_data Python Data3.csv')
pd.set_option('display.max_rows', 100)
df.head(50)

,Credit Policy,Interest Rate,Installments,Installment_as_Pct_Income,Log Annual Income,Annual Income,Monthly Income,Debt to Income Ratio,FICO Score,Days with Credit Line,...,Inquiries Last 6 Months,Delinquencies 2 Years,Public Records,Not Fully Paid,Purpose Credit Card,Purpose Debt Consolidation,Purpose Educational,Purpose Home Improvement,Purpose Major Purchase,Purpose Small Business
0,1,0.1189,829.10,0.117049,11.350407,85000.000380,7083.333365,0.1948,737,5640,...,0,0,0,0,0,1,0,0,0,0
1,1,0.1071,228.22,0.042133,11.082143,65000.000070,5416.666673,0.1429,707,2760,...,0,0,0,0,1,0,0,0,0,0
2,1,0.1357,366.86,0.137573,10.373491,31999.999940,2666.666662,0.1163,682,4710,...,1,0,0,0,0,1,0,0,0,0
3,1,0.1008,162.34,0.022919,11.350407,85000.000380,7083.333365,0.0810,712,2700,...,1,0,0,0,0,1,0,0,0,0
4,1,0.1426,102.92,0.015285,11.299732,80799.999640,6733.333303,0.1497,667,4066,...,0,1,0,0,1,0,0,0,0,0
5,1,0.0788,125.13,0.010146,11.904968,147999.999600,12333.333299,0.1698,727,6120,...,0,0,0,0,1,0,0,0,0,0
6,1,0.1496,194.02,0.051739,10.714418,45000.000060,3750.000005,0.0400,667,3180,...,0,0,1,1,0,1,0,0,0,0
7,1,0.1114,131.22,0.026244,11.002100,59999.999930,4999.999994,0.1108,722,5116,...,0,0,0,1,0,0,0,0,0,0
8,1,0.1134,87.19,0.011625,11.407565,90000.000060,7500.000005,0.1725,682,3989,...,1,0,0,0,0,0,0,1,0,0
9,1,0.1221,84.12,0.037387,10.203592,26999.999870,2249.999989,0.1000,707,2730,...,1,0,0,0,0,1,0,0,0,0
10,1,0.1347,360.43,0.127211,10.434116,33999.999880,2833.333323,0.2209,677,6713,...,2,0,1,0,0,1,0,0,0,0
11,1,0.1324,253.58,0.022050,11.835009,137999.999400,11499.999952,0.0916,662,4298,...,2,1,0,0,0,1,0,0,0,0
12,1,0.0859,316.11,0.067738,10.933107,56000.000020,4666.666668,0.1549,767,6520,...,0,0,0,0,0,1,0,0,0,0
13,1,0.0714,92.82,0.011138,11.512925,99999.999500,8333.333292,0.0650,747,4384,...,0,1,0,0,0,0,0,0,0,1
14,1,0.0863,209.54,0.190491,9.487972,13200.000010,1100.000000,0.0973,727,1560,...,0,0,0,0,0,1,0,0,0,0
15,1,0.1103,327.53,0.085228,10.738915,46115.999980,3842.999999,0.1304,702,8160,...,1,0,0,0,0,0,0,0,1,0
16,1,0.1317,77.69,0.025094,10.522773,37151.999830,3095.999986,0.0226,672,3896,...,0,0,0,0,0,0,0,0,0,0
17,1,0.0894,476.58,0.051991,11.608236,109999.999500,9166.666623,0.0707,797,6511,...,1,0,0,0,1,0,0,0,0,0
18,1,0.1039,584.12,0.194707,10.491274,36000.000090,3000.000008,0.0380,712,2760,...,0,0,0,0,0,1,0,0,0,0
19,1,0.1513,173.65,0.034730,11.002100,59999.999930,4999.999994,0.0274,667,1127,...,3,0,0,0,0,0,0,0,1,0
20,1,0.0800,188.02,0.030083,11.225243,74999.999810,6249.999984,0.1608,772,4889,...,1,0,0,0,0,0,0,0,0,0
21,1,0.0863,474.42,0.113861,10.819778,49999.999780,4166.666648,0.0259,797,11951,...,0,0,0,0,0,0,0,0,0,0
22,1,0.1355,339.60,0.040752,11.512925,99999.999500,8333.333292,0.0794,662,1940,...,0,0,0,0,1,0,0,0,0,0
23,1,0.0788,484.85,0.046546,11.736069,125000.000500,10416.666705,0.0705,782,5640,...,1,0,0,0,1,0,0,0,0,0
24,1,0.1229,320.19,0.049260,11.264464,78000.000340,6500.000028,0.0880,672,3761,...,0,0,1,0,0,1,0,0,0,0
25,1,0.0901,159.03,0.007633,12.429216,250000.000800,20833.333399,0.1000,712,1554,...,0,2,0,0,0,0,0,0,0,0
26,1,0.0743,155.38,0.028686,11.082143,65000.000070,5416.666673,0.0028,802,4650,...,1,0,0,0,0,0,0,0,0,0
27,1,0.1375,255.43,0.139325,9.998798,21999.999990,1833.333333,0.1429,662,1319,...,0,1,0,0,0,1,0,0,0,0
28,1,0.0743,155.38,0.009323,12.206073,200000.000900,16666.666741,0.0028,772,4517,...,0,0,0,0,0,0,0,0,0,0
29,1,0.0743,155.38,0.009323,12.206073,200000.000900,16666.666741,0.0372,812,6779,...,0,0,0,0,0,0,0,0,0,0
30,1,0.0807,156.84,0.018821,11.512925,99999.999500,8333.333292,0.0230,742,3149,...,0,0,0,0,0,1,0,0,0,0
31,1,0.1028,275.38,0.183587,9.798127,18000.000000,1500.000000,0.0640,692,7470,...,1,1,0,0,1,0,0,0,0,0
32,1,0.0743,155.38,0.012430,11.918391,149999.999500,12499.999962,0.0000,777,7129,...,0,0,0,0,0,0,0,1,0,0
33,1,0.0807,78.42,0.008555,11.608236,109999.999500,9166.666623,0.1133,762,6060,...,0,0,0,0,0,0,0,1,0,0
34,1,0.0870,158.30,0.025328,11.225243,74999.999810,6249.999984,0.1555,757,4770,...,0,0,0,0,1,0,0,0,0,0
35,1,0.0743,155.38,0.019627,11.461632,94999.999940,7916.666662,0.0383,772,2535,...,0,0,0,0,0,0,0,0,0,0
36,1,0.0743,155.38,0.021936,11.350407,85000.000380,7083.333365,0.0031,787,3540,...,0,0,0,0,1,0,0,0,0,0
37,1,0.1122,164.23,0.024635,11.289782,79999.999710,6666.666642,0.0121,672,3990,...,3,0,1,0,1,0,0,0,0,0
38,1,0.0996,161.25,0.040312,10.778956,48000.000010,4000.000000,0.0803,707,4320,...,1,0,0,0,0,1,0,0,0,0
39,1,0.0933,159.77,0.010651,12.100712,180000.000000,15000.000002,0.1193,717,4499,...,1,0,0,0,0,0,0,1,0,0
40,1,0.0807,156.84,0.010456,12.100712,180000.000000,15000.000002,0.0555,742,4019,...,0,0,0,0,0,0,0,1,0,0
41,1,0.0743,155.38,0.015538,11.695247,119999.999800,9999.999982,0.0229,777,3540,...,0,0,0,0,0,1,0,0,0,0
42,1,0.0870,94.98,0.045590,10.126631,24999.999900,2083.333325,0.1454,752,2460,...,1,0,0,0,0,0,0,0,0,1
43,1,0.1028,97.20,0.005832,12.206073,200000.000900,16666.666741,0.0000,677,3780,...,0,1,0,0,0,0,0,1,0,0
44,1,0.1122,164.23,0.065692,10.308953,29999.999980,2499.999998,0.1864,702,5190,...,0,0,0,0,1,0,0,0,0,0
45,1,0.0838,167.02,0.027084,11.211820,73999.999840,6166.666653,0.1437,797,5611,...,0,0,0,0,1,0,0,0,0,0
46,1,0.0775,168.60,0.252900,8.987197,8000.000003,666.666667,0.0300,762,6660,...,0,0,0,0,0,0,1,0,0,0
47,1,0.0838,160.72,0.060270,10.373491,31999.999940,2666.666662,0.1478,772,4379,...,0,0,0,0,0,0,0,0,0,0
48,1,0.0901,159.03,0.026142,11.198215,72999.999990,6083.333333,0.0996,722,3090,...,0,0,0,0,1,0,0,0,0,0
49,1,0.0743,178.69,0.017154,11.736069,125000.000500,10416.666705,0.0027,792,7489,...,0,0,0,0,0,1,0,0,0,0